apiVersion: apps/v1
kind: Deployment
metadata:
  name: aln-core
  labels:
    app: aln-core
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aln-core
  template:
    metadata:
      labels:
        app: aln-core
    spec:
      serviceAccountName: {{ .Values.rbac.serviceAccountName }}
      containers:
        - name: aln-core
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
          envFrom:
            - secretRef:
                name: aln-core-config
