{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aln-core
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aln-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aln-core
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccountName }}
{{- end }}
