apiVersion: v1
kind: Service
metadata:
  name: aln-core
  labels:
    app: aln-core
spec:
  selector:
    app: aln-core
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
